import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { WalletProvider, ConnectToMetaMask } from '@/feature/wallet'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <WalletProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Dogma</h1>
          <ConnectToMetaMask />
        </div>
      </main>
    </WalletProvider>
  )
}
